name = "r2-explorer"
compatibility_date = "2024-11-06"
main = "src/index.ts"
assets = { directory = "node_modules/r2-explorer/dashboard", binding = "ASSETS", html_handling = "auto-trailing-slash", not_found_handling = "single-page-application" }

# Bind R2 Buckets to your application.
# Docs: https://r2explorer.com/getting-started/add-r2-buckets/
[[r2_buckets]]
binding = "sd-chat"
bucket_name = "sd-chat"

[[r2_buckets]]
binding = "sundae-red-images"
bucket_name = "sundae-red-images"

[[r2_buckets]]
binding = "scrapes"
bucket_name = "scrapes"

[[r2_buckets]]
binding = "screenshots"
bucket_name = "screenshots"

[[r2_buckets]]
binding = "videos"
bucket_name = "videos"

[[r2_buckets]]
binding = "images"
bucket_name = "images"

[[r2_buckets]]
binding = "documents"
bucket_name = "documents"
